### PR TITLE
A Whole Bunch of Things

### PR DESCRIPTION
**Pull request by BeansBeefBroccoli**
This PR improves `bug_report.yml` and `mods.toml`, cleans up `gradle.yml, and `pack.mcmeta`, and adds `icon.png`.

Btw, what is magical log? I didn't modify it, but git thinks I did.

### CODE REVIEW

**Comment by Lvgraef** [comment]
the magical log is from my tree lol what did you do to it

**Comment by Lvgraef** [comment]
i did it like that for some reasons tho. becuase i have more stripable things and you didnt extend the rotated pillar block so it wont work i think

**Comment by BeansBeefBroccoli** [comment]
@Itskillerluc Git told me to put the magical log there, idk lol

**Comment by BeansBeefBroccoli** [comment]
@Itskillerluc Bump

Are you still working on this mod, or can I close this PR?

**Comment by Lvgraef** [comment]
You can close it. I’m only working on alchemical brewery rn

**Comment by BeansBeefBroccoli** [comment]
Ok thanks!

**Pull request closed without merging**
