### PR TITLE
Git Doesn't Like Me

### PR DESCRIPTION
**Pull request by BeansBeefBroccoli**
I thought this was all already merged but ig not.

### CODE REVIEW

**Comment by BeansBeefBroccoli** [comment]
Ok, Git really hates me now.

**Comment by Lvgraef** [comment]
this pull request has alerady been merged tho

**Comment by Lvgraef** [comment]
or does this add something new?

**Comment by BeansBeefBroccoli** [comment]
If I try to add something else, this will have to be merged anyways

**Comment by BeansBeefBroccoli** [comment]
Also, I did change the gradle.yml

**Comment by BeansBeefBroccoli** [comment]
Also, I don't think it hurts, it's just a weird git thing

**Comment by Lvgraef** [comment]
should i merge it?

**Comment by BeansBeefBroccoli** [comment]
It wouldn't hurt, also I did change gradle.yml a bit.

**Comment by Lvgraef** [comment]
squash and merge right

**Comment by BeansBeefBroccoli** [comment]
Yes.

**Pull request merged**
